version: '3'

services:
  db:
    image: postgres:11.9-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: courseware
      POSTGRES_USER: courseware
      POSTGRES_PASSWORD: coursewarepassword
    ports:
      - 5432:5432
    networks:
      - db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - db

  localstack:
    image: localstack/localstack:latest
    container_name: aba_courseware_localdev
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: 123
      AWS_SECRET_ACCESS_KEY: xyz
      SERVICES: s3,sqs,iam
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      KINESIS_PROVIDER: kinesalite
      LAMBDA_EXECUTOR: local
      LAMBDA_REMOTE_DOCKER: 0
      INIT_SCRIPTS_PATH: /tmp/localstack/init
      HOST_TMP_FOLDER: ${TMPDIR}
    volumes:
      #- './localstack:/tmp/localstack/data'
      - './onstart:/tmp/localstack/init'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"

networks:
  db:
    driver: bridge

volumes:
  db_data:
